name: Build and Publish N8N Python Docker Image

on:
  push:
    branches: [main]
    tags:
      - "*.*.*"
    paths:
      - ".github/workflows/docker-publish.yml"
      - "Dockerfile"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  buildtestpush:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.repository }}

    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ORAS
        id: install_oras
        uses: oras-project/setup-oras@main

      - name: Install Cosign
        id: install_cosign
        uses: sigstore/cosign-installer@v3.8.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: all

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        id: docker_hub_login
        if: github.event_name != 'pull_request' && contains(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        id: ghcr_login
        if: github.event_name != 'pull_request' && contains(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry (ORAS)
        id: oras_ghcr_login
        if: github.event_name != 'pull_request' && contains(github.ref, 'refs/tags/')
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | oras login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Publish Artifact Hub Manifest
        id: publish_ah_manifest
        if: github.event_name != 'pull_request' && contains(github.ref, 'refs/tags/')
        run: |
          oras push \
            ghcr.io/${{ env.IMAGE_NAME }}:artifacthub.io \
            --config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
            artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml

      - name: Extract Docker metadata
        if: github.event_name != 'pull_request' && contains(github.ref, 'refs/tags/')
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=ref,event=tag
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ env.IMAGE_NAME }}/refs/heads/main/README.md
            io.artifacthub.package.maintainers=[{"name":"burakince","email":"burak.ince@linux.org.tr"}]
            io.artifacthub.package.logo-url=https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
            io.artifacthub.package.keywords=n8n,workflow-automation,workflow,automation,ipaas,integration-framework,low-code-plattform,low-code
            io.artifacthub.package.license=MIT
            io.artifacthub.package.alternative-locations=docker.io/${{ env.IMAGE_NAME }}

      - name: Build image for local analysis
        id: build-docker-image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: docker.io/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Snyk to check Docker image for vulnerabilities
        id: docker-image-scan
        continue-on-error: true
        uses: snyk/actions/docker@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: docker.io/${{ env.IMAGE_NAME }}:latest
          args: --file=Dockerfile --severity-threshold=medium --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        if: hashFiles('snyk.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

      - name: Install Dive
        run: |
          set -e
          retries=3
          delay=5
          for ((i=1; i<=retries; i++)); do
            echo "Attempt $i of $retries"
            # Fetch the latest dive version
            DIVE_VERSION=$(curl -sL -H "Accept: application/vnd.github+json" "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
            if [ -z "$DIVE_VERSION" ]; then
              echo "Failed to fetch DIVE_VERSION"
              if [ $i -eq $retries ]; then
                echo "All attempts to fetch DIVE_VERSION failed"
                exit 1
              fi
              sleep $delay
              continue
            fi
            echo "DIVE_VERSION: $DIVE_VERSION"
            # Download the .deb file
            curl -OL --fail --retry 3 --retry-delay 5 "https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.deb"
            if [ $? -ne 0 ]; then
              echo "Failed to download dive_${DIVE_VERSION}_linux_amd64.deb"
              if [ $i -eq $retries ]; then
                echo "All attempts to download .deb file failed"
                exit 1
              fi
              sleep $delay
              continue
            fi
            # Verify the .deb file
            file dive_${DIVE_VERSION}_linux_amd64.deb | grep "Debian binary package" || {
              echo "Downloaded file is not a valid .deb package"
              if [ $i -eq $retries ]; then
                echo "All attempts to download a valid .deb file failed"
                exit 1
              fi
              rm -f dive_${DIVE_VERSION}_linux_amd64.deb
              sleep $delay
              continue
            }
            # Install the .deb file
            sudo apt install -y ./dive_${DIVE_VERSION}_linux_amd64.deb
            if [ $? -eq 0 ]; then
              echo "Dive installed successfully"
              exit 0
            else
              echo "Failed to install dive_${DIVE_VERSION}_linux_amd64.deb"
              if [ $i -eq $retries ]; then
                echo "All attempts to install dive failed"
                exit 1
              fi
              rm -f dive_${DIVE_VERSION}_linux_amd64.deb
              sleep $delay
            fi
          done

      - name: Analyse Efficiency and Wastes on Image
        run: dive docker.io/${{ env.IMAGE_NAME }}:latest

      - name: Ensure the image can be cross-compiled
        if: github.event_name == 'pull_request'
        id: build-and-push-pr
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64/v8,linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image
        if: github.event_name != 'pull_request' && contains(github.ref, 'refs/tags/')
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker images
        if: github.event_name != 'pull_request' && contains(github.ref, 'refs/tags/')
        run: |
          echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign -y {}@${{ steps.build-and-push.outputs.digest }}